<a href="https://colab.research.google.com/github/Blackerd/Lab_ML_2024/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1.1

In [1]:

#Input n integer numbers x1, x2,..., xn and append them into a list L.

L = []
n = int(input("Enter n: "))
for i in range(n):
    num = int(input("Enter element: "))
    L.append(num)
print("The list is:", L)

# Find the max/min element in L
max_element = max(L)
print("MAX:", max_element)

min_element = min(L)
print("MIN:", min_element)

#Compute the sum of elements in L
sum  = sum(L)
print("Sum  : ", sum)

# Sort the list L in ascending order
for i in range(len(L)):
    for j in range(len(L) - 1):
        if L[j] > L[j + 1]:
            L[j], L[j + 1] = L[j + 1], L[j]

print("The list in ascending order is:", L)

#Show how many positive and negative numbers are in the list L.
p = 0
n = 0
for num in L:
    if num > 0:
        p+= 1
    elif num < 0:
        n += 1
print("Number of positive numbers:", p)
print("Number of negative numbers:", n)






Enter n: 3
Enter element: 3
Enter element: 6
Enter element: 9
The list is: [3, 6, 9]
MAX: 9
MIN: 3
Sum  :  18
The list in ascending order is: [3, 6, 9]
Number of positive numbers: 3
Number of negative numbers: 0


Task 1.2

In [2]:
#. Implement a Python function to compute S(n)
n = int(input("Enter n: "))
def compute_S(n):
    p = 1
    sum = 0
    for i in range(1, n + 1):
        p *= i
        sum += p
    return sum
print(f"S({n}) =", compute_S(n))


Enter n: 5
S(5) = 153


Task 1.3

In [3]:
from typing import List

class Post:
    def __init__(self, content: str, subject: str, likes: int):
        self.content = content
        self.subject = subject
        self.likes = likes

class Account:
    def __init__(self, name: str, email: str, country: str, friends: List['Account'], posts: List[Post]):
        self.name = name
        self.email = email
        self.country = country
        self.friends = friends
        self.posts = posts

    def getMaxLikePostByFriend(self) -> 'Account':
        max_likes_account = None
        max_likes = 0

        for friend in self.friends:
            for post in friend.posts:
                if post.likes > max_likes:
                    max_likes = post.likes
                    max_likes_account = friend

        return max_likes_account

class AccountManager:
    def __init__(self, accounts: List[Account]):
        self.accounts = accounts

    def groupAccountsByPostLike(self) -> dict:
      grouped_accounts = {True: [], False: []}

      for account in self.accounts:
          if len(account.posts) < 10:
              grouped_accounts[False].append(account)
          else:
              grouped_accounts[True].append(account)
      return grouped_accounts


    def filterAccounts(self, country: str) -> set:
      filtered_accounts = [account for account in self.accounts if account.country == country]

      sorted_accounts = sorted(filtered_accounts, key=lambda account: (-len(account.posts), account.name))

      return sorted_accounts


import unittest

class Test(unittest.TestCase):
    def setUp(self):
        self.post1 = Post('content1', 'subject1', 5)
        self.post2 = Post('content2', 'subject2', 10)
        self.post3 = Post('content3', 'subject3', 15)

        self.account1 = Account('name1', 'email1', 'Vietnam', [], [self.post1, self.post2])
        self.account2 = Account('name2', 'email2', 'USA', [self.account1], [self.post3])

        self.accountManager = AccountManager([self.account1, self.account2])


    def test_getMaxLikePostByFriend(self):
        self.assertEqual(self.account2.getMaxLikePostByFriend(), self.account1)
        max_likes_account_name = self.account2.getMaxLikePostByFriend().name
        print("Tài khoản có bài đăng với lượt thích cao nhất:", max_likes_account_name)

    def test_groupAccountsByPostLike(self):
        grouped_accounts = self.accountManager.groupAccountsByPostLike()
        self.assertEqual(grouped_accounts, {True: [self.account2], False: [self.account1]})
        print("Nhóm tài khoản:", {k: [account.name for account in v] for k, v in grouped_accounts.items()})

    def test_filterAccounts(self):
        filtered_accounts = self.accountManager.filterAccounts('Vietnam')
        self.assertEqual(filtered_accounts, [self.account1])
        print("Tài khoản được lọc:", [account.name for account in filtered_accounts])




Task 2.1

In [4]:
import numpy as np

arr = np.arange(0, 10)
print("Mảng gốc:", arr)

reversed_arr = np.flip(arr)
print("Mảng đã đảo ngược:", reversed_arr)


Mảng gốc: [0 1 2 3 4 5 6 7 8 9]
Mảng đã đảo ngược: [9 8 7 6 5 4 3 2 1 0]


Task 2.2

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

arr2 = np.tile(arr, 2)
print("Repeating 2 times:", arr2)

arr3 = np.tile(arr, 3)
print("Repeating 3 times:", arr3)


Original array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3

In [6]:
import numpy as np

arr = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.51, 0.34, 0.15]])
print("Original array:\n", arr)

arr[arr > 0.5] = 0.5
print("Array after replacement:\n", arr)


Original array:
 [[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Array after replacement:
 [[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
